### ISSUE TITLE
Implement ALG_ID 6602 (CALG_RC2)

### ISSUE THREAD

**Issue by syntroniks** [crappycrypto/wincrypto#1]
RC2 may or may not be good or bad. Needless to say, I need it from this python library. Pull request incoming (hopefully)

**Comment by syntroniks** [comment]
Shouldn't be too hard to implement, but for whatever reason tests fail on my machine (after forking, without modifications). I'll just use ctypes

**Comment by gakar06** [comment]
Any update on this being implemented in wincrypto?

**Comment by crappycrypto** [comment]
After a long delay a partial RC2 implementation is included in the latest commit. For now the support is 128bit only, but if you still need this feel free to submit a pull request.
