### ISSUE TITLE
This library is broken for both Python 2 and 3

### ISSUE THREAD

**Issue by Ana06** [crappycrypto/wincrypto#3]
Since https://github.com/crappycrypto/wincrypto/commit/5f6c060ed86b04045060f29c306be8879988da0f this library doesn't seems to work.

The test upstream are failing as you can see in the last build: https://travis-ci.org/crappycrypto/wincrypto/builds/34218593 Some tests return `1` instead of `ok` but Travis is not taking those failures into account. This may have caused it to be unnoticed.

I removed the last two commits and that version seems to work for Python 2.

**Comment by crappycrypto** [comment]
The extra print(1) in tests is now removed. And the code runs fine on my machine under the latest python 2.7 on windows 10. If you still encounter problems feel free to re-open/re-submit this issue.
